/**
 * Re-exports the compiled flash-loan contract module for the browser.
 *
 * The module is generated by `compact compile` (repo root: `npm run compile`)
 * and copied here by `npm run copy-zk-assets`:
 *   - `Contract`          — contract class, bound to witnesses at runtime
 *   - `ledger`            — decodes the public ledger from an indexer state
 *
 * Only this file knows the contract artifacts; the rest of the frontend works
 * against the loosely-typed `CompiledContract` produced in contract-service.
 */

export { Contract, ledger, pureCircuits } from '../compiled-contract.js';
